### ISSUE TITLE
FizzBuzz

### ISSUE THREAD

**Issue by davidmarek** [ivo172/Vyuka_Python#1]
Napis program, ktery vypise cisla od 1 do 100. Pro nasobky 3 misto cisla vypize "Fizz". Pro nasobky 5 vypise "Buzz" a pro cisla ktera jsou nasobkem 3 i 5 vypise "FizzBuzz".

**Comment by ivo172** [comment]
ok

**Comment by ivo172** [comment]
Mrkni se na to, proc ta funkce if .. nejde. Nechci reseni ukolu, k tomu se nejak dopracuji. Ale tady jsem se zasek.

**Comment by ivo172** [comment]
Uz jsem na to prisel, neres, pokracuji. Jsem ... nedal jsem uvozovky.

**Comment by ivo172** [comment]
Hotovo, ukol splnen!

**Comment by ivo172** [comment]
Opraveno. Snad uz dobre.
